### ISSUE TITLE
Nested slide-up-downs

### ISSUE THREAD

**Issue by ellismonva** [craigrileyuk/vue3-slide-up-down#2]
Hey. Great package - although I noticed something that's not working as expected. When nesting <slide-up-down> elements (in my case I have a parent and child), the height is not changing correctly on the parent if the child <slide-up-down> is shown (the red error message shown in the screenshot is hidden by default and is a <slide-up-down>). 

I believe this is because my parent <slide-up-down> has a height (say 200px when the height transition has ended (should it be changed to auto when the transition has finished?).

I hope this makes sense?

<img width="1343" alt="Screenshot 2021-07-27 at 16 00 26" src="https://user-images.githubusercontent.com/86981893/127177756-ab7743a7-33d9-4d61-b0e1-8e5db34ae07c.png">

**Comment by craigrileyuk** [comment]
Have you tried using the <slide-up-down ... responsive> prop on the component?

**Comment by ellismonva** [comment]
I set :responsive="true" on both parent and children and I was still seeing the same as above

**Comment by craigrileyuk** [comment]
Thanks for the detailed feedback.

Resolved in 6a61d81a00d7f83b265ced9456ada6ca94d37269
