### ISSUE TITLE
Issue with height: auto on close transition

### ISSUE THREAD

**Issue by ellismonva** [craigrileyuk/vue3-slide-up-down#3]
Hi,

[https://github.com/craigrileyuk/vue3-slide-up-down/commit/6a61d81a00d7f83b265ced9456ada6ca94d37269](https://github.com/craigrileyuk/vue3-slide-up-down/commit/6a61d81a00d7f83b265ced9456ada6ca94d37269)

As per the above release, I have noticed an issue that is directly tied to this. 

[Video](https://www.loom.com/share/cdd69777f2284940a4de674b8835401b)

Because we are setting the height to auto at the end of the open transition, the close transition is not working as expected when the item is closed (because its trying to animate from height auto to {x} height). I think in this case, we need to add the height back when the close transition starts for it to be smooth.

Extra note: instead of setting the height to auto on the open transition end, it may be best removing the height property on the element instead (https://developer.mozilla.org/en-US/docs/Web/API/Element/removeAttribute)? I believe this is what slide-up-down-2 does.

**Comment by craigrileyuk** [comment]
Closed with 3b8198e760eb0d889fe30e5c8f20cedb4349d279

**Comment by ellismonva** [comment]
Perfect, thank you @craigrileyuk
