### ISSUE TITLE
Set height is causing issues when slide-up-down is visible by default

### ISSUE THREAD

**Issue by ellismonva** [craigrileyuk/vue3-slide-up-down#4]
Hi,

I have just spotted an issue - when I am showing the slide up down component by default (for example below)..

` <slide-up-down v-model="true"  :responsive="true" ></slide-up-down>`

When the height of the container changes, this is causing an issue for me as per the below video (maybe makes sense to remove the height by default?):

https://www.loom.com/share/6ef7c6e0ab9549598f87051d77e3538d

**Comment by craigrileyuk** [comment]
Closed with 3b8198e760eb0d889fe30e5c8f20cedb4349d279

**Comment by ellismonva** [comment]
Perfect, thank you @craigrileyuk

**Comment by ellismonva** [comment]
Hi @craigrileyuk,
It seems this is working for me on local after testing - but on my staging environment, seems to be broken.. (pic below)

![c4a5d64a-e7a9-4071-8a40-6bab92c9525c](https://user-images.githubusercontent.com/86981893/129915368-f8548cea-9fbd-49a9-a883-e3c1446c6b61.png)

I am using version 1.2.0 for my local and staging.

The staging is using below..
<img width="848" alt="Screenshot 2021-08-18 at 15 21 59" src="https://user-images.githubusercontent.com/86981893/129915569-3cb644a9-80fd-4c99-b953-ed4f05bdc92e.png">

Would you have any idea why it is behaving differently on separate environments?
