### ISSUE TITLE
open-end being triggered endlessly

### ISSUE THREAD

**Issue by gaby64** [craigrileyuk/vue3-slide-up-down#6]
open-end is being triggered endlessly when interacting (moving mouse over or focusing inputs) with the content of the slide-up-down, I have a form in it.

**Comment by gaby64** [comment]
probably missing 

`if (event.target !== this.el) return`

in onTransitionEnd

**Comment by craigrileyuk** [comment]
Thanks for the pull request for this one.

Closed with 8a58373661c27e8005f349f8110177bab7027d12
