### ISSUE TITLE
Negative tab index when closed

### ISSUE THREAD

**Issue by ellismonva** [craigrileyuk/vue3-slide-up-down#8]
Hi,
Is it possible to add a tab-index of -1 when the a container is closed (I noticed some tabbing issues)? I could do this myself but thought it would be a useful future for the actual package.

Thanks

**Comment by craigrileyuk** [comment]
I've added it to the attributes when closed, but I don't think it affects child elements (i.e. inputs inside the container element). If this doesn't work, I might look into using v-if to remove the container's rendering when closed.

**Comment by ellismonva** [comment]
Thanks craig @craigrileyuk
