### ISSUE TITLE
Height problem on responsive prop

### ISSUE THREAD

**Issue by ellismonva** [craigrileyuk/vue3-slide-up-down#9]
Hi,
Noticed a minor issue:

As seen in the below video, (i have the responsive prop as true in this container), the height of the container does actually resize sometimes, however it's not always consistent and has a bigger height size than the content.

https://www.loom.com/share/6f6cfe14313c4cbaa1797f187e974f86

Thanks

**Comment by Sitronik** [comment]
I have the same problem, responsive is not working correctly. A little later I will create a PR that solves this problem.

**Comment by Sitronik** [comment]
@ellismonva try this package
`npm i vue3-slide-up-down-fix`

**Comment by craigrileyuk** [comment]
> Hi, Noticed a minor issue:
> 
> As seen in the below video, (i have the responsive prop as true in this container), the height of the container does actually resize sometimes, however it's not always consistent and has a bigger height size than the content.

Hi @ellismonva, I'm trying to track down this issue. Could you post the HTML code that you're using with the v-slide-up-down tag by any chance?

**Comment by craigrileyuk** [comment]
I think I've identified and fixed the issue with ac5a127. Seemed to be caused by the v-model being updated during a transition.

**Comment by ellismonva** [comment]
Perfect thanks @craigrileyuk
